export type ToolMode = "local" | "external-lookup";
export type ToolStatus = "ready" | "planned";
export type ToolIcon = "fingerprint" | "key" | "link-off" | "braces" | "lock" | "scan" | "file-text" | "video";

export type ToolCategory = "Network" | "Privacy" | "Security" | "Files" | "Developer";

export type ToolDefinition = {
  slug: string;
  name: string;
  description: string;
  category: ToolCategory;
  mode: ToolMode;
  status: ToolStatus;
  icon: ToolIcon;
  privacyNotice: string;
  /** Surfaced on the homepage. The full set always lives at /tools. */
  featured?: boolean;
};

export const toolRegistry: ToolDefinition[] = [
  {
    slug: "video-toolkit",
    name: "Private Video Toolkit",
    description: "Trim, resize, crop, compress, mute, and capture thumbnails from your own videos without uploading them.",
    category: "Files",
    mode: "local",
    status: "ready",
    icon: "video",
    privacyNotice: "The selected video is read and processed in browser memory. It is never uploaded, and NoTrak does not fetch videos from social platforms.",
    featured: true,
  },
  {
    slug: "resume-builder",
    name: "Private Resume Builder",
    description: "Build a clean resume with a live preview and download a selectable-text PDF. No account or upload needed.",
    category: "Files",
    mode: "local",
    status: "ready",
    icon: "file-text",
    privacyNotice: "Resume content and draft files are processed in your browser, not uploaded. Nothing is autosaved. Download a local draft to keep your work.",
    featured: true,
  },
  {
    slug: "whats-my-ip",
    name: "What’s My IP",
    description: "See the public address and approximate location visible to this connection.",
    category: "Network",
    mode: "external-lookup",
    status: "ready",
    icon: "fingerprint",
    privacyNotice: "Your request IP is read once to return this result. No application history is saved.",
    featured: true,
  },
  {
    slug: "password-generator",
    name: "Password Generator",
    description: "Create strong, unique passwords using secure randomness on your device.",
    category: "Security",
    mode: "local",
    status: "ready",
    icon: "key",
    privacyNotice: "Generated entirely in your browser. Your password never leaves this device.",
    featured: true,
  },
  {
    slug: "password-safety",
    name: "Password Safety Checker",
    description: "Analyze password strength locally and optionally check a privacy-preserving breach range.",
    category: "Security",
    mode: "external-lookup",
    status: "ready",
    icon: "key",
    privacyNotice: "Strength analysis stays in your browser. After confirmation, only a five-character SHA-1 hash prefix is sent directly to Have I Been Pwned, which also receives your request IP.",
    featured: true,
  },
  {
    slug: "tracking-url-cleaner",
    name: "Tracking URL Cleaner",
    description: "Strip common advertising and campaign parameters before sharing a link.",
    category: "Privacy",
    mode: "local",
    status: "ready",
    icon: "link-off",
    privacyNotice: "Cleaned entirely in your browser. The submitted link is never opened or sent to NoTrak.",
    featured: true,
  },
  {
    slug: "sensitive-data-redactor",
    name: "Sensitive Data Redactor",
    description: "Find and replace common personal details, credentials, and secrets before sharing text.",
    category: "Privacy",
    mode: "local",
    status: "ready",
    icon: "scan",
    privacyNotice: "Text and selected files are inspected and sanitized only in your browser.",
    featured: true,
  },
  {
    slug: "hash-generator",
    name: "Hash Generator",
    description: "Calculate secure file and text fingerprints without uploading content.",
    category: "Developer",
    mode: "local",
    status: "ready",
    icon: "braces",
    privacyNotice: "Files and text are processed only in your browser.",
  },
  {
    slug: "passphrase-generator",
    name: "Passphrase Generator",
    description: "Create memorable multi-word passphrases with secure on-device randomness.",
    category: "Security",
    mode: "local",
    status: "ready",
    icon: "key",
    privacyNotice: "Generated entirely in your browser from a bundled word list.",
  },
  {
    slug: "uuid-generator",
    name: "UUID Generator",
    description: "Generate standards-based unique identifiers locally.",
    category: "Developer",
    mode: "local",
    status: "ready",
    icon: "braces",
    privacyNotice: "Identifiers are generated only in your browser.",
  },
  {
    slug: "qr-generator",
    name: "QR Generator",
    description: "Turn text or a link into a downloadable QR code.",
    category: "Developer",
    mode: "local",
    status: "ready",
    icon: "scan",
    privacyNotice: "QR content is processed only in your browser.",
  },
  {
    slug: "exif-viewer",
    name: "EXIF Viewer",
    description: "See the camera, timestamp, and location data hidden inside a photo.",
    category: "Privacy",
    mode: "local",
    status: "ready",
    icon: "scan",
    privacyNotice: "The image is read only in your browser. Coordinates are never sent to a map service.",
  },
  {
    slug: "remove-exif",
    name: "EXIF Remover",
    description: "Create a clean image copy without embedded camera metadata.",
    category: "Files",
    mode: "local",
    status: "ready",
    icon: "scan",
    privacyNotice: "Images are read and rewritten only on your device.",
    featured: true,
  },
  {
    slug: "image-compressor",
    name: "Image Compressor",
    description: "Reduce image size locally while keeping the original untouched.",
    category: "Files",
    mode: "local",
    status: "ready",
    icon: "scan",
    privacyNotice: "Images are compressed only in your browser.",
  },
  {
    slug: "image-resizer",
    name: "Image Resizer",
    description: "Resize an image to exact dimensions without uploading it.",
    category: "Files",
    mode: "local",
    status: "ready",
    icon: "scan",
    privacyNotice: "The image is decoded, resized, and exported only in your browser.",
  },
  {
    slug: "image-to-text",
    name: "Image to Text",
    description: "Extract editable text from a screenshot or photo without uploading it.",
    category: "Files",
    mode: "local",
    status: "ready",
    icon: "scan",
    privacyNotice: "The image is read by a bundled OCR engine in your browser. No image or recognized text is uploaded.",
    featured: true,
  },
  {
    slug: "file-encryption",
    name: "File Encryption",
    description: "Encrypt sensitive files locally before storing or sending them.",
    category: "Files",
    mode: "local",
    status: "ready",
    icon: "lock",
    privacyNotice: "Files, passwords, and keys never leave your browser.",
    featured: true,
  },
  {
    slug: "browser-privacy",
    name: "Browser Privacy Check",
    description: "Understand information a normal website can observe about this browser.",
    category: "Privacy",
    mode: "local",
    status: "ready",
    icon: "fingerprint",
    privacyNotice: "The check runs locally and does not claim to prove anonymity.",
  },
  {
    slug: "speed-test",
    name: "Speed Test",
    description: "Measure connection speed, latency, and jitter from the browser.",
    category: "Network",
    mode: "external-lookup",
    status: "ready",
    icon: "fingerprint",
    privacyNotice: "Measurement traffic goes directly to Cloudflare, which receives your IP address. No typed content or files are sent; result logging is disabled.",
  },
  {
    slug: "pdf-metadata-cleaner",
    name: "PDF Metadata Cleaner",
    description: "Remove document metadata and download a new PDF copy.",
    category: "Files",
    mode: "local",
    status: "ready",
    icon: "lock",
    privacyNotice: "PDF files are processed only in your browser.",
  },
  {
    slug: "pdf-toolkit",
    name: "PDF Toolkit",
    description: "Merge, reorder, rotate, remove, or split PDF pages without uploading documents.",
    category: "Files",
    mode: "local",
    status: "ready",
    icon: "lock",
    privacyNotice: "PDF documents and their pages are organized only in your browser.",
  },
  {
    slug: "phishing-checker",
    name: "Phishing Checker",
    description: "Inspect suspicious links using explainable checks and reputation sources.",
    category: "Security",
    mode: "external-lookup",
    status: "ready",
    icon: "scan",
    privacyNotice: "Local checks stay in-browser. After confirmation, the full URL is sent through NoTrak to configured Google Safe Browsing and URLhaus providers.",
  },
  {
    slug: "email-header-analyzer",
    name: "Email Header Analyzer",
    description: "Trace a suspicious message's delivery path and sender authentication without uploading it.",
    category: "Security",
    mode: "local",
    status: "ready",
    icon: "scan",
    privacyNotice: "Headers are parsed only in your browser. Recipient names, internal server names, and the sending IP address are never uploaded or logged.",
    featured: true,
  },
  {
    slug: "malware-reputation",
    name: "Malware Reputation",
    description: "Check whether a locally calculated SHA-256 hash is known to threat intelligence.",
    category: "Security",
    mode: "external-lookup",
    status: "ready",
    icon: "scan",
    privacyNotice: "The file stays local. After confirmation, only its SHA-256 hash is sent through NoTrak to MalwareBazaar.",
  },
  {
    slug: "qr-scanner",
    name: "QR Scanner",
    description: "Read QR codes from a selected image or camera with explicit permission.",
    category: "Privacy",
    mode: "local",
    status: "ready",
    icon: "scan",
    privacyNotice: "Images and camera frames are processed only in your browser.",
  },
  {
    slug: "image-converter",
    name: "Image Converter",
    description: "Convert supported image formats locally and download the result.",
    category: "Files",
    mode: "local",
    status: "ready",
    icon: "scan",
    privacyNotice: "Images are converted only in your browser.",
  },
  {
    slug: "base64-converter",
    name: "Base64 Converter",
    description: "Encode text to Base64 or decode it back, including the URL-safe alphabet.",
    category: "Developer",
    mode: "local",
    status: "ready",
    icon: "braces",
    privacyNotice: "Encoded and decoded entirely in your browser.",
  },
  {
    slug: "json-formatter",
    name: "JSON Formatter",
    description: "Format, minify, and validate JSON with the exact error location.",
    category: "Developer",
    mode: "local",
    status: "ready",
    icon: "braces",
    privacyNotice: "Parsed only in your browser. A pasted payload is never sent anywhere.",
  },
  {
    slug: "text-encryption",
    name: "Text Encryption",
    description: "Encrypt a message into a pasteable block, and decrypt one you receive.",
    category: "Security",
    mode: "local",
    status: "ready",
    icon: "lock",
    privacyNotice: "The message, password, and derived key never leave your browser.",
  },
  {
    slug: "jwt-decoder",
    name: "JWT Decoder",
    description: "Inspect token headers and payloads without pretending to verify a signature.",
    category: "Developer",
    mode: "local",
    status: "ready",
    icon: "braces",
    privacyNotice: "Token contents are decoded only in your browser.",
  },
];

export const toolCategories: ToolCategory[] = ["Network", "Privacy", "Security", "Files", "Developer"];

export const readyTools = toolRegistry.filter((tool) => tool.status === "ready");

export const featuredTools = readyTools.filter((tool) => tool.featured);

export function getTool(slug: string) {
  return toolRegistry.find((tool) => tool.slug === slug);
}
